### ISSUE TITLE
Cooperation

### ISSUE THREAD

**Issue by Free-IPTV** [christiankaye/radio_television#1]
Hi @christiankaye,

do you want to cooprate us?

We have a private repo with over 80 m3u's, currently 3997 free and legal streams.

You live in the USA, you are practically at the source. We are also interested in the many small TV channels, that's what we have US02_USA_Local.m3u for. Maybe you have a few tips for new streams from the USA every now and then. The only important thing is that there is no geo-blocking in the streams.

You can think about it and let me know here.

Greetings

Free IPTV

**Comment by christiankaye** [comment]
Yes, I would like to cooperate with you. All the channels in my repo are free, legal and unblocked. Also, they are all nationwide, Christian television and radio stations. Three are from Spain (LOGOS-TV). That's what I can manage at this time.

**Comment by Free-IPTV** [comment]
Hi @christiankaye,

okay, I'm sending you an invitation, come in without a donation. I think we can talk to each other well, but as far as streams are concerned, please read the readme in the private repo. 

To a good cooperation :-)

**Comment by Free-IPTV** [comment]
Hi @christiankaye ,

invitation is sending out, it comes with your Github-Email. :-)

**Comment by christiankaye** [comment]
Hi, I found this in my drafts email folder. I thought I had replied to you. My apologies. 
Yes, sir. I want to cooperate with you and help Free-IPTV as I am able.

Christian K.


On April 13, 2021 4:22:12 AM CDT, Free-IPTV ***@***.***> wrote:

Hi https://github.com/christiankaye,

do you want to cooprate us?

We have a private repo with over 80 m3u's, currently 3997 free and legal streams.

You live in the USA, you are practically at the source. We are also interested in the many small TV channels, that's what we have US02_USA_Local.m3u for. Maybe you have a few tips for new streams from the USA every now and then. The only important thing is that there is no geo-blocking in the streams.

You can think about it and let me know here.

Greetings

Free IPTV
